version: "3"
services:
  admin:
    build: admin
    command: yarn dev
    ports:
      - "8800:3000"
    volumes:
      - ./admin:/app
      - /app/node_modules
    depends_on:
      - api
    env_file:
      - ./admin/.env.local
  api:
    build: api
    command: yarn dev
    ports:
      - "8801:3000"
      - "9229:9229"
    volumes:
      - ./api:/app
      - /app/node_modules
    depends_on:
      - db
    environment:
      NODE_ENV: development
      ODDNAAN_PORT: 3000
      ODDNAAN_PGHOST: db
      ODDNAAN_PGUSER: oddnaan-app
      ODDNAAN_PGDATABASE: oddnaan
      ODDNAAN_PGPASSWORD: coolpassword
      ODDNAAN_PGPORT: 5432
      ODDNAAN_AUTH_SECRET: m0n4l!s4
      ODDNAAN_S3_ENDPOINT: sfo2.digitaloceanspaces.com
      ODDNAAN_S3_ACCESS_KEY_ID: cool-key-id
      ODDNAAN_S3_ACCESS_KEY_SECRET: cool-key-secret
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: coolpassword
      POSTGRES_USER: oddnaan-app
      POSTGRES_DB: oddnaan
    ports:
      - "15432:5432"
